name: YubiKitTests

on: [push]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build for device
        run: |
          cd YubiKit
          ./build.sh
          cd ..
                        
      - name: Test on emulator
        run: |
          set -o pipefail && xcodebuild -sdk iphonesimulator -workspace YubiKit.xcworkspace -scheme YubiKit -destination "platform=iOS Simulator,OS=latest,name=iPhone 11" test | xcpretty --test --color
         
      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: yubikit-ios
          path: YubiKit/releases
